# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cutoffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutOff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('university_type', models.CharField(choices=[('H', 'Home'), ('O', 'Other')], default='Other', max_length=128)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cutoffs.Branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cutoffs.Category')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cutoffs.College')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cutoffs.Gender')),
            ],
        ),
    ]
