# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutoffs', '0002_cutoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoff',
            name='cet_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cutoff',
            name='merit_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
