# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutoffs', '0003_auto_20160312_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoff',
            name='admission_round',
            field=models.IntegerField(default=1),
        ),
    ]
